InlineYouTube: fix WebpageMediaEmptyError
🚫 Form invoke failed!

🧾 Logs:
  File "/home/ubuntu/Hikka/hikka/inline/form.py", line 307, in form
    m = await q[0].click(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telethon/tl/custom/inlineresult.py", line 173, in click
    return self._client._get_response_message(req, await self._client(req), entity)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telethon/client/users.py", line 32, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "<core api>", line 185, in new_call
  File "/home/ubuntu/Hikka/hikka/tl_cache.py", line 337, in _call
    return await TelegramClient._call(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telethon/client/users.py", line 92, in _call
    result = await future
telethon.errors.rpcerrorlist.WebpageMediaEmptyError: Webpage media empty (caused by SendInlineBotResultRequest)