ImageBoardSender: fix init db
🚫 [ERROR] hikka.loader: Failed to send mod init complete signal for <hikka.modules.BooruModel.ImageBoardSenderMod object at 0x7f64a8eb80> due to 'NoneType' object is not iterable, attempting unload
Traceback (most recent call last):
  File "/home/cakestwix/Hikka/hikka/loader.py", line 734, in send_ready_one
    await mod.client_ready(client, db)
  File "<string>", line 324, in client_ready
  File "<string>", line 292, in _init
  File "<string>", line 36, in rating_string
TypeError: 'NoneType' object is not iterable🚫 [ERROR] hikka.modules.loader: Module threw because 'NoneType' object is not iterable
Traceback (most recent call last):
  File "<core>", line 670, in load_module
  File "/home/cakestwix/Hikka/hikka/loader.py", line 734, in send_ready_one
    await mod.client_ready(client, db)
  File "<string>", line 324, in client_ready
  File "<string>", line 292, in _init
  File "<string>", line 36, in rating_string
TypeError: 'NoneType' object is not iterable