InlineYouTube: error fixes and pre-selection of quality
telethon.errors.rpcerrorlist.WebpageMediaEmptyError: Webpage media empty (caused by SendInlineBotResultRequest)