tikcock: Catch BotResponseTimeoutError and return message
🚫 Command .dttnw https://vt.tiktok.com/ZSdU2eJbC/ failed!

⛑ Traceback:
  File "/home/pi/Desktop/bots/Hikka/hikka/dispatcher.py", line 453, in future_dispatcher
    await func(message)
  File "https://gitlab.com/CakesTwix/friendly-userbot-modules/-/raw/master/tikcock.py", line 41, in dttnwcmd
    r = await message.client.inline_query("tikdobot", args)
  File "/home/pi/.local/lib/python3.9/site-packages/telethon/client/bots.py", line 65, in inline_query
    result = await self(
  File "/home/pi/.local/lib/python3.9/site-packages/telethon/client/users.py", line 32, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/pi/.local/lib/python3.9/site-packages/telethon/client/users.py", line 92, in _call
    result = await future
telethon.errors.rpcerrorlist.BotResponseTimeoutError: The bot did not answer to the callback query in time (caused by GetInlineBotResultsRequest)